window.QUANT_FACTORS = {
  "factors": [
    {
      "factor_id": "legacy_bs@0",
      "name": "legacy_bs",
      "version": 0,
      "family": "balance_sheet",
      "direction": 1,
      "horizon_m": 3,
      "level": "stock",
      "hypothesis": "Legacy factor migration from V18",
      "formula": "raw",
      "inputs_json": "[]",
      "lookback_days": 252,
      "applies_to_financials": 1,
      "backfillable": 1,
      "min_coverage": 0.5,
      "evidence": "legacy_migration",
      "hypothesis_id": null,
      "code_sha256": "legacy_sha",
      "module_path": "quant.factors.legacy",
      "status": "shadow",
      "registered_on": "2026-06-01T00:00:00.000000Z",
      "first_live_as_of": null,
      "status_changed_on": "2026-06-01T00:00:00.000000Z",
      "status_decision_id": null
    },
    {
      "factor_id": "legacy_cap_alloc@0",
      "name": "legacy_cap_alloc",
      "version": 0,
      "family": "cap_alloc",
      "direction": 1,
      "horizon_m": 3,
      "level": "stock",
      "hypothesis": "Legacy factor migration from V18",
      "formula": "raw",
      "inputs_json": "[]",
      "lookback_days": 252,
      "applies_to_financials": 1,
      "backfillable": 1,
      "min_coverage": 0.5,
      "evidence": "legacy_migration",
      "hypothesis_id": null,
      "code_sha256": "legacy_sha",
      "module_path": "quant.factors.legacy",
      "status": "shadow",
      "registered_on": "2026-06-01T00:00:00.000000Z",
      "first_live_as_of": null,
      "status_changed_on": "2026-06-01T00:00:00.000000Z",
      "status_decision_id": null
    },
    {
      "factor_id": "legacy_dc_flag@0",
      "name": "legacy_dc_flag",
      "version": 0,
      "family": "momentum",
      "direction": -1,
      "horizon_m": 3,
      "level": "stock",
      "hypothesis": "Legacy factor migration from V18",
      "formula": "raw",
      "inputs_json": "[]",
      "lookback_days": 252,
      "applies_to_financials": 1,
      "backfillable": 1,
      "min_coverage": 0.5,
      "evidence": "legacy_migration",
      "hypothesis_id": null,
      "code_sha256": "legacy_sha",
      "module_path": "quant.factors.legacy",
      "status": "shadow",
      "registered_on": "2026-06-01T00:00:00.000000Z",
      "first_live_as_of": null,
      "status_changed_on": "2026-06-01T00:00:00.000000Z",
      "status_decision_id": null
    },
    {
      "factor_id": "legacy_growth@0",
      "name": "legacy_growth",
      "version": 0,
      "family": "growth",
      "direction": 1,
      "horizon_m": 3,
      "level": "stock",
      "hypothesis": "Legacy factor migration from V18",
      "formula": "raw",
      "inputs_json": "[]",
      "lookback_days": 252,
      "applies_to_financials": 1,
      "backfillable": 1,
      "min_coverage": 0.5,
      "evidence": "legacy_migration",
      "hypothesis_id": null,
      "code_sha256": "legacy_sha",
      "module_path": "quant.factors.legacy",
      "status": "shadow",
      "registered_on": "2026-06-01T00:00:00.000000Z",
      "first_live_as_of": null,
      "status_changed_on": "2026-06-01T00:00:00.000000Z",
      "status_decision_id": null
    },
    {
      "factor_id": "legacy_moat@0",
      "name": "legacy_moat",
      "version": 0,
      "family": "moat",
      "direction": 1,
      "horizon_m": 3,
      "level": "stock",
      "hypothesis": "Legacy factor migration from V18",
      "formula": "raw",
      "inputs_json": "[]",
      "lookback_days": 252,
      "applies_to_financials": 1,
      "backfillable": 1,
      "min_coverage": 0.5,
      "evidence": "legacy_migration",
      "hypothesis_id": null,
      "code_sha256": "legacy_sha",
      "module_path": "quant.factors.legacy",
      "status": "shadow",
      "registered_on": "2026-06-01T00:00:00.000000Z",
      "first_live_as_of": null,
      "status_changed_on": "2026-06-01T00:00:00.000000Z",
      "status_decision_id": null
    },
    {
      "factor_id": "legacy_momentum_multiplier@0",
      "name": "legacy_momentum_multiplier",
      "version": 0,
      "family": "momentum",
      "direction": 1,
      "horizon_m": 3,
      "level": "stock",
      "hypothesis": "Legacy factor migration from V18",
      "formula": "raw",
      "inputs_json": "[]",
      "lookback_days": 252,
      "applies_to_financials": 1,
      "backfillable": 1,
      "min_coverage": 0.5,
      "evidence": "legacy_migration",
      "hypothesis_id": null,
      "code_sha256": "legacy_sha",
      "module_path": "quant.factors.legacy",
      "status": "shadow",
      "registered_on": "2026-06-01T00:00:00.000000Z",
      "first_live_as_of": null,
      "status_changed_on": "2026-06-01T00:00:00.000000Z",
      "status_decision_id": null
    },
    {
      "factor_id": "legacy_quality@0",
      "name": "legacy_quality",
      "version": 0,
      "family": "quality",
      "direction": 1,
      "horizon_m": 3,
      "level": "stock",
      "hypothesis": "Legacy factor migration from V18",
      "formula": "raw",
      "inputs_json": "[]",
      "lookback_days": 252,
      "applies_to_financials": 1,
      "backfillable": 1,
      "min_coverage": 0.5,
      "evidence": "legacy_migration",
      "hypothesis_id": null,
      "code_sha256": "legacy_sha",
      "module_path": "quant.factors.legacy",
      "status": "shadow",
      "registered_on": "2026-06-01T00:00:00.000000Z",
      "first_live_as_of": null,
      "status_changed_on": "2026-06-01T00:00:00.000000Z",
      "status_decision_id": null
    },
    {
      "factor_id": "legacy_risk@0",
      "name": "legacy_risk",
      "version": 0,
      "family": "risk",
      "direction": -1,
      "horizon_m": 3,
      "level": "stock",
      "hypothesis": "Legacy factor migration from V18",
      "formula": "raw",
      "inputs_json": "[]",
      "lookback_days": 252,
      "applies_to_financials": 1,
      "backfillable": 1,
      "min_coverage": 0.5,
      "evidence": "legacy_migration",
      "hypothesis_id": null,
      "code_sha256": "legacy_sha",
      "module_path": "quant.factors.legacy",
      "status": "shadow",
      "registered_on": "2026-06-01T00:00:00.000000Z",
      "first_live_as_of": null,
      "status_changed_on": "2026-06-01T00:00:00.000000Z",
      "status_decision_id": null
    },
    {
      "factor_id": "legacy_smart_money@0",
      "name": "legacy_smart_money",
      "version": 0,
      "family": "smart_money",
      "direction": 1,
      "horizon_m": 3,
      "level": "stock",
      "hypothesis": "Legacy factor migration from V18",
      "formula": "raw",
      "inputs_json": "[]",
      "lookback_days": 252,
      "applies_to_financials": 1,
      "backfillable": 1,
      "min_coverage": 0.5,
      "evidence": "legacy_migration",
      "hypothesis_id": null,
      "code_sha256": "legacy_sha",
      "module_path": "quant.factors.legacy",
      "status": "shadow",
      "registered_on": "2026-06-01T00:00:00.000000Z",
      "first_live_as_of": null,
      "status_changed_on": "2026-06-01T00:00:00.000000Z",
      "status_decision_id": null
    },
    {
      "factor_id": "legacy_trap@0",
      "name": "legacy_trap",
      "version": 0,
      "family": "trap",
      "direction": -1,
      "horizon_m": 3,
      "level": "stock",
      "hypothesis": "Legacy factor migration from V18",
      "formula": "raw",
      "inputs_json": "[]",
      "lookback_days": 252,
      "applies_to_financials": 1,
      "backfillable": 1,
      "min_coverage": 0.5,
      "evidence": "legacy_migration",
      "hypothesis_id": null,
      "code_sha256": "legacy_sha",
      "module_path": "quant.factors.legacy",
      "status": "shadow",
      "registered_on": "2026-06-01T00:00:00.000000Z",
      "first_live_as_of": null,
      "status_changed_on": "2026-06-01T00:00:00.000000Z",
      "status_decision_id": null
    },
    {
      "factor_id": "legacy_valuation@0",
      "name": "legacy_valuation",
      "version": 0,
      "family": "value",
      "direction": 1,
      "horizon_m": 3,
      "level": "stock",
      "hypothesis": "Legacy factor migration from V18",
      "formula": "raw",
      "inputs_json": "[]",
      "lookback_days": 252,
      "applies_to_financials": 1,
      "backfillable": 1,
      "min_coverage": 0.5,
      "evidence": "legacy_migration",
      "hypothesis_id": null,
      "code_sha256": "legacy_sha",
      "module_path": "quant.factors.legacy",
      "status": "shadow",
      "registered_on": "2026-06-01T00:00:00.000000Z",
      "first_live_as_of": null,
      "status_changed_on": "2026-06-01T00:00:00.000000Z",
      "status_decision_id": null
    }
  ],
  "contracts": []
};
